### ISSUE TITLE
Trouble compiling the template in handlebars

### ISSUE THREAD

**Issue by ochorocho** [foundation/supercollider#19]
When calling the suppercollider using this line:
```
./node_modules/supercollider/bin/supercollider.js --source ../meta.wiki/ --template ./template-new.html
```
it fails to compile the handlebars template:

```
/Users/XXX/Php_Projekte/collider_test/node_modules/supercollider/lib/config.js:27
    this.template = this.options.handlebars.compile(fileData.toString(), {noEscape: true});
                                            ^

TypeError: this.options.handlebars.compile is not a function
    at Supercollider.module.exports [as config] (/Users/XXX/Php_Projekte/collider_test/node_modules/supercollider/lib/config.js:27:45)
    at Object.<anonymous> (/Users/XXX/Php_Projekte/collider_test/node_modules/supercollider/bin/supercollider.js:18:7)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```
As a base for the Template i used this `./node_modules/supercollider/test/fixtures/template.html`

**Comment by ncoden** [comment]
Hi @ochorocho. I forgot to take care of this. I'll take a look when I have some free time. I'm very busy right now with the Foundation v6.5 release & professional stuff.

**Comment by ochorocho** [comment]
no worries :-)
thanks for working on this.

**Comment by ochorocho** [comment]
Updated all dependencies in https://github.com/ochorocho/supercollider

Tests working now:
```
> mocha

  Supercollider.adapter()
    ✓ loads built-in adapters (323ms)
    ✓ throws an error if you try to load a non-existant built-in adapter
    ✓ loads custom adapters
    ✓ throws an error if you use a reserved keyword as an adapter name
    ✓ throws an error if you try to pass something other than a function as an adapter

  Supercollider.build()
    ✓ builds an HTML file from the data of a page (59ms)
    ✓ adds global data to the Handlebars instance
    ✓ catches Handlebars errors
    ✓ allows Front Matter to be retained on the page (58ms)

  Supercollider.buildSearch()
(node:30611) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    ✓ works even if searchConfig() was not called (65ms)
    ✓ flags generic pages as "page" (38ms)
    ✓ flags pages with code hooks as "component" (309ms)
    ✓ allows for custom page types
    ✓ creates a JSON file of search results (434ms)
    ✓ allows extra external results to be added (398ms)

  Supercollider.config()
    ✓ sets configuration settings
    ✓ throws an error if no template is defined
    ✓ throws an error if the template cannot be loaded

  Supercollider.init()
    ✓ parses and builds a documentation page
    ✓ works within a stream of Vinyl files if src and dest are omitted
    ✓ resets the internal data tree on each build
    ✓ allows for incremental builds

  Supercollider.parse()
    ✓ converts Markdown into HTML
    ✓ does not touch Markdown if configured to ignore it
    ✓ loads data from adapters
    ✓ catches Markdown errors

  Supercollider.searchConfig()
    ✓ loads JSON data
    ✓ loads YAML data

  Supercollider constructor
    ✓ creates a new instance of Supercollider
    ✓ sets blank defaults for config settings

```

Todo:
* [ ] There is one dependencies that fails due to `severity vulnerability` , check `npm audit`
* [ ] Check if things are working now as described at the beginnning of this issue.

**Comment by joeworkman** [comment]
Closing this. I will be releasing an updated version with all new upgraded dependencies.
